services:
  php:
    build:
      context: . # ruta de referencia ./
      dockerfile: ./Dockerfile # nombre del archivo de configuracion de la imagen
    container_name: reportefallasbackend-php #
    volumes:
      - ./:/var/www
    user: "${UID}:${GID}"
    ports:
      - 9000:80
    depends_on:
      - mysql
    networks:
      - reportefallas # red

  nginx:
    image: nginx:stable-alpine # imagen de docker hub que vamos a usar
    container_name: reportefallasbackend-nginx # nombre para referirse al servicio
    ports:
      - 8000:80
    volumes:
      - ./:/var/www # carpeta local/ vincula a carpeta de nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # archivo local / reflejado en archivo de la imagen
    depends_on:
      - php
    networks:
      - reportefallas

  mysql:
    image: mysql:8.0
    container_name: reportefallasbackend-mysql
    environment:
      MYSQL_DATABASE: reportefallas
      MYSQL_ROOT_PASSWORD: Luis1984.
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3308:3306 # 3306 ocupado por MySQL nativo del host, 3307 por otro proyecto (vemitiendabackend-mysql)
    networks:
      - reportefallas


networks:
  reportefallas:

volumes:
  mysql_data:
